CREATE TABLE IF NOT EXISTS cotizaciones_acceso (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL,
    empresa VARCHAR(100),
    referencia VARCHAR(50) NOT NULL,
    referencia_otro VARCHAR(100),
    direccion TEXT NOT NULL,
    tipo_inmueble VARCHAR(50) NOT NULL,
    tipo_inmueble_otro VARCHAR(100),
    cantidad_accesos VARCHAR(20) NOT NULL,
    tipo_acceso VARCHAR(100) NOT NULL,
    tipo_acceso_otro VARCHAR(100),
    metodo_autenticacion VARCHAR(100) NOT NULL,
    metodo_autenticacion_otro VARCHAR(100),
    bitacora VARCHAR(20) NOT NULL,
    integracion_sistema VARCHAR(20) NOT NULL,
    puertas_compatibles VARCHAR(20) NOT NULL,
    suministro_electrico VARCHAR(20) NOT NULL,
    red_internet VARCHAR(20) NOT NULL,
    cantidad_usuarios VARCHAR(20) NOT NULL,
    gestion_web VARCHAR(20) NOT NULL,
    horarios_acceso VARCHAR(20) NOT NULL,
    tiempo_instalacion VARCHAR(50) NOT NULL,
    mantenimiento VARCHAR(50) NOT NULL,
    horario_contacto VARCHAR(20) NOT NULL,
    comentarios TEXT,
    fecha_creacion DATETIME NOT NULL,
    estado ENUM('pendiente', 'en_proceso', 'completado', 'cancelado') DEFAULT 'pendiente',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL,
    empresa VARCHAR(100),
    referencia VARCHAR(50) NOT NULL,
    referencia_otro VARCHAR(100),
    direccion TEXT NOT NULL,
    tipo_inmueble VARCHAR(50) NOT NULL,
    tipo_inmueble_otro VARCHAR(100),
    cantidad_accesos VARCHAR(20) NOT NULL,
    tipo_acceso VARCHAR(100) NOT NULL,
    tipo_acceso_otro VARCHAR(100),
    metodo_autenticacion VARCHAR(100) NOT NULL,
    metodo_autenticacion_otro VARCHAR(100),
    bitacora VARCHAR(20) NOT NULL,
    integracion_sistema VARCHAR(20) NOT NULL,
    puertas_compatibles VARCHAR(20) NOT NULL,
    suministro_electrico VARCHAR(20) NOT NULL,
    red_internet VARCHAR(20) NOT NULL,
    cantidad_usuarios VARCHAR(20) NOT NULL,
    gestion_web VARCHAR(20) NOT NULL,
    horarios_acceso VARCHAR(20) NOT NULL,
    tiempo_instalacion VARCHAR(50) NOT NULL,
    mantenimiento VARCHAR(50) NOT NULL,
    horario_contacto VARCHAR(20) NOT NULL,
    comentarios TEXT,
    fecha_creacion DATETIME NOT NULL,
    estado ENUM('pendiente', 'en_proceso', 'completado', 'cancelado') DEFAULT 'pendiente',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 