CREATE TABLE IF NOT EXISTS cotizaciones_camaras (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL,
    empresa VARCHAR(100),
    referencia VARCHAR(50) NOT NULL,
    referencia_otro VARCHAR(100),
    direccion TEXT NOT NULL,
    tipo_propiedad VARCHAR(50) NOT NULL,
    tipo_propiedad_otro VARCHAR(100),
    cantidad_camaras VARCHAR(20) NOT NULL,
    tipo_camaras VARCHAR(20) NOT NULL,
    vision_nocturna VARCHAR(20) NOT NULL,
    visualizacion_remota VARCHAR(20) NOT NULL,
    almacenamiento VARCHAR(50) NOT NULL,
    red_electrica VARCHAR(20) NOT NULL,
    red_internet VARCHAR(20) NOT NULL,
    infraestructura_previo VARCHAR(20) NOT NULL,
    tiempo_instalacion VARCHAR(50) NOT NULL,
    horario_contacto VARCHAR(20) NOT NULL,
    comentarios TEXT,
    comentarios_admin TEXT,
    fecha_creacion DATETIME NOT NULL,
    estado ENUM('pendiente', 'en_proceso', 'completado', 'cancelado') DEFAULT 'pendiente',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL,
    empresa VARCHAR(100),
    referencia VARCHAR(50) NOT NULL,
    referencia_otro VARCHAR(100),
    direccion TEXT NOT NULL,
    tipo_propiedad VARCHAR(50) NOT NULL,
    tipo_propiedad_otro VARCHAR(100),
    cantidad_camaras VARCHAR(20) NOT NULL,
    tipo_camaras VARCHAR(20) NOT NULL,
    vision_nocturna VARCHAR(20) NOT NULL,
    visualizacion_remota VARCHAR(20) NOT NULL,
    almacenamiento VARCHAR(50) NOT NULL,
    red_electrica VARCHAR(20) NOT NULL,
    red_internet VARCHAR(20) NOT NULL,
    infraestructura_previo VARCHAR(20) NOT NULL,
    tiempo_instalacion VARCHAR(50) NOT NULL,
    horario_contacto VARCHAR(20) NOT NULL,
    comentarios TEXT,
    comentarios_admin TEXT,
    fecha_creacion DATETIME NOT NULL,
    estado ENUM('pendiente', 'en_proceso', 'completado', 'cancelado') DEFAULT 'pendiente',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 
 